const INPUT_CHANGE = 'INPUT_CHANGE'
const OUTPUT_CHANGE = 'OUTPUT_CHANGE'
const STAKE_TYPE = 'STAKE_TYPE'
const INPUTTOKEN = 'INPUTTOKEN'
const OUTPUTTOKEN = 'OUTPUTTOKEN'
const TRIGGER = 'TRIGGER'

export {
  INPUT_CHANGE,
  OUTPUT_CHANGE,
  STAKE_TYPE,
  INPUTTOKEN,
  OUTPUTTOKEN,
  TRIGGER
}